version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - DATABASE_ID=${DATABASE_ID:-2d09071e8c8480b491efe553bc776324}
      - DATABASE_VIEW_ID_DB1=${DATABASE_VIEW_ID_DB1:-2d09071e8c8480ada01d000c833708d1}
      - DATABASE_VIEW_ID_DB2=${DATABASE_VIEW_ID_DB2:-2d09071e8c8480acbba7000c1810635d}
      - NOTION_API_VERSION=${NOTION_API_VERSION:-2025-09-03}
